package index;

import Connection.Connect;
import index.admin.Jasa;
import index.admin.Pengambilan;
import index.admin.Statistik;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DashboardAdminPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form DataAdmin
     */
    public DashboardAdminPelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnpegawai = new javax.swing.JButton();
        btnpelanggan = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btn_statistik = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        icon_statistik = new javax.swing.JLabel();
        btn_jasa = new javax.swing.JPanel();
        icon_jasa1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_pengambilan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        icon_pengambilan1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        btnpegawai.setBackground(new java.awt.Color(111, 200, 255));
        btnpegawai.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnpegawai.setText("DATA PEGAWAI");
        btnpegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpegawai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpegawaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpegawaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpegawaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpegawaiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnpegawaiMouseReleased(evt);
            }
        });
        getContentPane().add(btnpegawai);
        btnpegawai.setBounds(0, 100, 260, 80);

        btnpelanggan.setBackground(new java.awt.Color(204, 255, 255));
        btnpelanggan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnpelanggan.setText("DATA PELANGGAN");
        btnpelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnpelanggan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(btnpelanggan);
        btnpelanggan.setBounds(0, 180, 260, 80);

        btnkeluar.setBackground(new java.awt.Color(111, 200, 255));
        btnkeluar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnkeluar.setText("LOGOUT");
        btnkeluar.setPreferredSize(new java.awt.Dimension(89, 27));
        btnkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnkeluarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnkeluarMouseReleased(evt);
            }
        });
        getContentPane().add(btnkeluar);
        btnkeluar.setBounds(70, 690, 89, 27);

        btn_statistik.setBackground(new java.awt.Color(111, 200, 255));
        btn_statistik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_statistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_statistikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_statistikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_statistikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_statistikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_statistikMouseReleased(evt);
            }
        });
        btn_statistik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STATISTIK");
        btn_statistik.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, 200, -1));

        icon_statistik.setBackground(new java.awt.Color(51, 204, 255));
        icon_statistik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_statistik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/STATISTIK.png"))); // NOI18N
        icon_statistik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_statistik.setPreferredSize(new java.awt.Dimension(240, 290));
        icon_statistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_statistikMouseClicked(evt);
            }
        });
        btn_statistik.add(icon_statistik, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 100));

        getContentPane().add(btn_statistik);
        btn_statistik.setBounds(1080, 300, 210, 260);

        btn_jasa.setBackground(new java.awt.Color(111, 200, 255));
        btn_jasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_jasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_jasaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_jasaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_jasaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_jasaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_jasaMouseReleased(evt);
            }
        });
        btn_jasa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_jasa1.setBackground(new java.awt.Color(51, 204, 255));
        icon_jasa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_jasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/JASAZ.png"))); // NOI18N
        icon_jasa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_jasa1.setPreferredSize(new java.awt.Dimension(240, 290));
        icon_jasa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_jasa1MouseClicked(evt);
            }
        });
        btn_jasa.add(icon_jasa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, 100));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("JASA");
        btn_jasa.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, -1));

        getContentPane().add(btn_jasa);
        btn_jasa.setBounds(340, 300, 210, 260);

        btn_pengambilan.setBackground(new java.awt.Color(111, 200, 255));
        btn_pengambilan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pengambilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengambilanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pengambilanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pengambilanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_pengambilanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_pengambilanMouseReleased(evt);
            }
        });
        btn_pengambilan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PENGAMBILAN");
        btn_pengambilan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 210, 200, -1));

        icon_pengambilan1.setBackground(new java.awt.Color(51, 204, 255));
        icon_pengambilan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_pengambilan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/PENGAMBILANZ.png"))); // NOI18N
        icon_pengambilan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_pengambilan1.setPreferredSize(new java.awt.Dimension(240, 290));
        icon_pengambilan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_pengambilan1MouseClicked(evt);
            }
        });
        btn_pengambilan.add(icon_pengambilan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 110));

        getContentPane().add(btn_pengambilan);
        btn_pengambilan.setBounds(730, 300, 210, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1366x768/dashboard admin.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 768);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnpegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpegawaiMouseEntered
        // TODO add your handling code here:
        btnpegawai.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnpegawaiMouseEntered

    private void btnpegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpegawaiMouseExited
        // TODO add your handling code here:
        btnpegawai.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnpegawaiMouseExited

    private void btnpegawaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpegawaiMousePressed
        // TODO add your handling code here:
        btnpegawai.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnpegawaiMousePressed

    private void btnpegawaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpegawaiMouseReleased
        // TODO add your handling code here:
        btnpegawai.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnpegawaiMouseReleased

    private void btnkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseEntered
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnkeluarMouseEntered

    private void btnkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseExited
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnkeluarMouseExited

    private void btnkeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMousePressed
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnkeluarMousePressed

    private void btnkeluarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseReleased
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnkeluarMouseReleased

    private void btnkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseClicked
        Logout();
    }//GEN-LAST:event_btnkeluarMouseClicked

    private void btnpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpegawaiMouseClicked
        // TODO add your handling code here:
        new DashboardAdminPegawai().setVisible(true);
    }//GEN-LAST:event_btnpegawaiMouseClicked

    private void btnpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpelangganActionPerformed
        // TODO add your handling code here:
        btnpelanggan.setEnabled(false);
    }//GEN-LAST:event_btnpelangganActionPerformed

    private void icon_statistikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_statistikMouseClicked
        new Statistik().setVisible(true);
    }//GEN-LAST:event_icon_statistikMouseClicked

    private void btn_statistikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_statistikMouseReleased
        // TODO add your handling code here:
        btn_statistik.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btn_statistikMouseReleased

    private void btn_statistikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_statistikMouseEntered
        // TODO add your handling code here:
        btn_statistik.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btn_statistikMouseEntered

    private void btn_statistikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_statistikMouseExited
        btn_statistik.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btn_statistikMouseExited

    private void btn_statistikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_statistikMousePressed
        btn_statistik.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btn_statistikMousePressed

    private void btn_statistikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_statistikMouseClicked
        // TODO add your handling code here:
         new Statistik().setVisible(true);
    }//GEN-LAST:event_btn_statistikMouseClicked

    private void icon_jasa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_jasa1MouseClicked
        btn_jasa.setBackground(new Color(58, 106, 135));
        new Jasa().setVisible(true);
    }//GEN-LAST:event_icon_jasa1MouseClicked

    private void btn_jasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jasaMouseClicked
        new Jasa().setVisible(true);
    }//GEN-LAST:event_btn_jasaMouseClicked

    private void btn_jasaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jasaMouseEntered
        btn_jasa.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btn_jasaMouseEntered

    private void btn_jasaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jasaMouseExited
        btn_jasa.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btn_jasaMouseExited

    private void btn_jasaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jasaMousePressed
        btn_jasa.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btn_jasaMousePressed

    private void btn_jasaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jasaMouseReleased
        btn_jasa.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btn_jasaMouseReleased

    private void icon_pengambilan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_pengambilan1MouseClicked
        // TODO add your handling code here:
        new Pengambilan().setVisible(true);
        icon_pengambilan1.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_icon_pengambilan1MouseClicked

    private void btn_pengambilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengambilanMouseClicked
        // TODO add your handling code here:
        btn_pengambilan.setBackground(new Color(58, 106, 135));
        new Pengambilan().setVisible(true); 
    }//GEN-LAST:event_btn_pengambilanMouseClicked

    private void btn_pengambilanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengambilanMouseEntered
        btn_pengambilan.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btn_pengambilanMouseEntered

    private void btn_pengambilanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengambilanMouseExited
        // TODO add your handling code here:
        btn_pengambilan.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btn_pengambilanMouseExited

    private void btn_pengambilanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengambilanMousePressed
        // TODO add your handling code here:
        btn_pengambilan.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btn_pengambilanMousePressed

    private void btn_pengambilanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengambilanMouseReleased
        btn_pengambilan.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btn_pengambilanMouseReleased

    public void Logout() {
        int a = JOptionPane.showConfirmDialog(null, "Switch User?");
        switch (a) {
            case JOptionPane.YES_OPTION:
                new FORM_SwitchUser().setVisible(true);
                this.dispose();
                break;
            case JOptionPane.NO_OPTION:
                System.exit(0);
            default:
                break;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardAdminPelanggan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_jasa;
    private javax.swing.JPanel btn_pengambilan;
    private javax.swing.JPanel btn_statistik;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnpegawai;
    private javax.swing.JButton btnpelanggan;
    private javax.swing.JLabel icon_jasa1;
    private javax.swing.JLabel icon_pengambilan1;
    private javax.swing.JLabel icon_statistik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
