/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package index;

import Connection.Connect;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class DashboardPegawaiStatistik extends javax.swing.JFrame {

    /**
     * Creates new form DatapegawaiPengambilan
     */
    private DefaultTableModel tabelcd;

    private void showTable() {
        tabelcd = new DefaultTableModel();
        table.setModel(tabelcd);
        tabelcd.addColumn("No");
        tabelcd.addColumn("Bulan / Tanggal");
        tabelcd.addColumn("Keterangan");
        tabelcd.addColumn("Biaya Pengeluaran");
        tabelcd.addColumn("Biaya Pemasukan");
        tabelcd.addColumn("Pendapatan Bersih");
        // menampilkan database ke dalam tabel
        try {
            int no = 1;
            String sql = "SELECT * FROM statistik ";
            java.sql.Connection conn = (Connection) Connect.ConfigDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                tabelcd.addRow(new Object[]{
                    res.getString("No"),
                    res.getString("tanggal"),
                    res.getString("nama_barang"),
                    res.getString("biaya_pengeluaran"),
                    res.getString("biaya_pemasukan"),
                    res.getString("pendapatan_bersih")});
            }
            table.setModel(tabelcd);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void search() {

        tabelcd = new DefaultTableModel();
        table.setModel(tabelcd);
        tabelcd.addColumn("No");
        tabelcd.addColumn("Bulan / Tanggal");
        tabelcd.addColumn("Keterangan");
        tabelcd.addColumn("Biaya Pengeluaran");
        tabelcd.addColumn("Biaya Pemasukan");
        tabelcd.addColumn("Pendapatan Bersih");
        // menampilkan database ke dalam tabel
        String search = txt_search.getText();
        try {
            int no = 1;
            String sql = "SELECT * FROM statistik WHERE No='" + search + "'"
            +"or no LIKE '%"+ search + "%'";
            java.sql.Connection conn = (Connection) Connect.ConfigDB();
            try ( java.sql.Statement stm = conn.createStatement();  java.sql.ResultSet res = stm.executeQuery(sql)) {
                while (res.next()) {
                    tabelcd.addRow(new Object[]{
                        res.getString("No"),
                        res.getString("tanggal"),
                        res.getString("nama_barang"),
                        res.getString("biaya_pengeluaran"),
                        res.getString("biaya_pemasukan"),
                        res.getString("pendapatan_bersih"),});
                }
                table.setModel(tabelcd);
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void kosong() {
        table.setModel(tabelcd);
        tabelcd.addColumn("No");
        tabelcd.addColumn("Bulan / Tanggal");
        tabelcd.addColumn("Keterangan");
        tabelcd.addColumn("Biaya Pengeluaran");
        tabelcd.addColumn("Biaya Pemasukan");
        tabelcd.addColumn("Pendapatan Bersih");
    }

    public void tanggal() {
        DateFormat tgl = new SimpleDateFormat("Y-M-d");
        String htgl = tgl.format(Calendar.getInstance().getTime());
    }

    public DashboardPegawaiStatistik() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnkeluar = new javax.swing.JButton();
        btn_statistik = new javax.swing.JButton();
        btn_jasa = new javax.swing.JButton();
        btn_pengambilan = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_re = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        cal_tgl1 = new com.toedter.calendar.JDateChooser();
        cal_tgl2 = new com.toedter.calendar.JDateChooser();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/X PNG.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnkeluar.setBackground(new java.awt.Color(111, 200, 255));
        btnkeluar.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        btnkeluar.setText("LOGOUT");
        btnkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnkeluarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnkeluarMouseReleased(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, -1, -1));

        btn_statistik.setBackground(new java.awt.Color(204, 255, 255));
        btn_statistik.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btn_statistik.setText("STATISTIK");
        btn_statistik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_statistik.setPreferredSize(new java.awt.Dimension(360, 100));
        btn_statistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statistikActionPerformed(evt);
            }
        });
        getContentPane().add(btn_statistik, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 260, 70));

        btn_jasa.setBackground(new java.awt.Color(111, 200, 255));
        btn_jasa.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btn_jasa.setText("JASA");
        btn_jasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_jasa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_jasa.setPreferredSize(new java.awt.Dimension(360, 100));
        btn_jasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jasaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_jasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 70));

        btn_pengambilan.setBackground(new java.awt.Color(111, 200, 255));
        btn_pengambilan.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btn_pengambilan.setText("PENGAMBILAN");
        btn_pengambilan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pengambilan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pengambilan.setPreferredSize(new java.awt.Dimension(360, 100));
        btn_pengambilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengambilanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pengambilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, 70));

        btn_tambah.setBackground(new java.awt.Color(51, 153, 255));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(20);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 1030, 430));

        btn_re.setBackground(new java.awt.Color(51, 153, 255));
        btn_re.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_re.setText("REFRESH");
        btn_re.setPreferredSize(new java.awt.Dimension(30, 30));
        btn_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reActionPerformed(evt);
            }
        });
        getContentPane().add(btn_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 130, 80, 30));

        btn_cetak.setBackground(new java.awt.Color(51, 153, 255));
        btn_cetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cetak.setText("CETAK");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 170, 80, 30));

        cal_tgl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cal_tgl1KeyReleased(evt);
            }
        });
        getContentPane().add(cal_tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 180, 30));

        cal_tgl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cal_tgl2KeyReleased(evt);
            }
        });
        getContentPane().add(cal_tgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 170, 180, 30));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 130, 60, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("s.d");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, -1, -1));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1366x768/dashboard pelanggan.png"))); // NOI18N
        getContentPane().add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jasaActionPerformed
        new DashboardPegawaiJasa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_jasaActionPerformed

    private void btnkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Switch User?");
        switch (a) {
            case JOptionPane.YES_OPTION:
                new FORM_SwitchUser().setVisible(true);
                this.dispose();
                break;
            case JOptionPane.NO_OPTION:
                System.exit(0);
            default:
                break;
        }
    }//GEN-LAST:event_btnkeluarMouseClicked

    private void btnkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseEntered
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnkeluarMouseEntered

    private void btnkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseExited
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnkeluarMouseExited

    private void btnkeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMousePressed
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnkeluarMousePressed

    private void btnkeluarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseReleased
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnkeluarMouseReleased

    private void btn_pengambilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengambilanActionPerformed
        // TODO add your handling code here:
        new DashboardPegawaiPengambilan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_pengambilanActionPerformed

    private void btn_statistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statistikActionPerformed
        // TODO add your handling code here:
        btn_statistik.setEnabled(false);
    }//GEN-LAST:event_btn_statistikActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        new input_statistik().setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reActionPerformed
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_btn_reActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed

        try {
            String nota2 = ("C:\\Users\\yoni_\\Documents\\New folder\\SistemPengelolahDataKasir\\berliantExport\\src\\laporan\\Laporan.jrxml"); //link file directorylaporan / struk
            HashMap hash = new HashMap();   //hashmap
            hash.put("tgl1", cal_tgl1.getDate()); //mengambil parameter hash dari search
            hash.put("tgl2", cal_tgl2.getDate()); //mengambil parameter hash dari search
            JasperReport JRpt = JasperCompileManager.compileReport(nota2);  //menyiapkan data nota2
            JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, Connect.ConfigDB());  //print
            JasperViewer.viewReport(JPrint, false); //jika Jprint ditutup tidak akan mengEksekusi System.exit(0);
        } catch (SQLException | JRException rptexcpt) {
            JOptionPane.showMessageDialog(null, "Masukkan No. pelanggan");
        }

    }//GEN-LAST:event_btn_cetakActionPerformed

    private void cal_tgl1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cal_tgl1KeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_cal_tgl1KeyReleased

    private void cal_tgl2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cal_tgl2KeyReleased
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_cal_tgl2KeyReleased

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        search(); //tanpa klik search
    }//GEN-LAST:event_txt_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPegawaiJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPegawaiJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPegawaiJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPegawaiJasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardPegawaiStatistik().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background1;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_jasa;
    private javax.swing.JButton btn_pengambilan;
    private javax.swing.JButton btn_re;
    private javax.swing.JButton btn_statistik;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btnkeluar;
    private com.toedter.calendar.JDateChooser cal_tgl1;
    private com.toedter.calendar.JDateChooser cal_tgl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

}
