package index;

import Connection.Connect;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

@SuppressWarnings("unchecked")
public class DashboardAdminPegawai extends javax.swing.JFrame {

    /**
     * Creates new form DataAdmin
     */
    public DashboardAdminPegawai() {
        initComponents();

        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnhapus = new javax.swing.JButton();
        btnpegawai = new javax.swing.JButton();
        btnpelanggan = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        btnhapus.setBackground(new java.awt.Color(51, 153, 255));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus);
        btnhapus.setBounds(390, 690, 93, 33);

        btnpegawai.setBackground(new java.awt.Color(204, 255, 255));
        btnpegawai.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnpegawai.setText("DATA PEGAWAI");
        btnpegawai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnpegawai);
        btnpegawai.setBounds(0, 100, 260, 80);

        btnpelanggan.setBackground(new java.awt.Color(111, 200, 255));
        btnpelanggan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnpelanggan.setText("DATA PELANGGAN");
        btnpelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpelanggan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpelangganMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpelangganMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnpelangganMouseReleased(evt);
            }
        });
        getContentPane().add(btnpelanggan);
        btnpelanggan.setBounds(0, 180, 260, 80);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search);
        txt_search.setBounds(1000, 170, 200, 30);

        btnkeluar.setBackground(new java.awt.Color(111, 200, 255));
        btnkeluar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnkeluar.setText("LOGOUT");
        btnkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnkeluarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnkeluarMouseReleased(evt);
            }
        });
        getContentPane().add(btnkeluar);
        btnkeluar.setBounds(70, 690, 89, 27);

        table.setAutoCreateRowSorter(true);
        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 240, 920, 430);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SEARCH");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1220, 160, 80, 40);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1366x768/dashboard admin.png"))); // NOI18N
        BG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BG.setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1366, 768);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public DefaultTableModel tabelcd; //Default tabel modelnya saya kasih nama 'tabelcd'

    private void showTable() {
        tabelcd = new DefaultTableModel();
        table.setModel(tabelcd);
        tabelcd.addColumn("Username");
        tabelcd.addColumn("Password");
        tabelcd.addColumn("Nama");
        tabelcd.addColumn("Alamat");
        tabelcd.addColumn("KTP");
        tabelcd.addColumn("Telepon");
        tabelcd.addColumn("Jenis Kelamin");
        tabelcd.addColumn("Level");

        // menampilkan database ke dalam tabel
        try {
            String sql = "SELECT * FROM data_karyawan";
            java.sql.Connection conn = (Connection) Connect.ConfigDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                tabelcd.addRow(new Object[]{
                    res.getString("username"),
                    res.getString("password"),
                    res.getString("nama"),
                    res.getString("alamat"),
                    res.getString("no_ktp"),
                    res.getString("no_telpn"),
                    res.getString("jenis_kelamin"),
                    res.getString("level"),});
            }
            table.setModel(tabelcd);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void btnpelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpelangganMouseEntered
        // TODO add your handling code here:
        btnpelanggan.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnpelangganMouseEntered

    private void btnpelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpelangganMouseExited
        // TODO add your handling code here:
        btnpelanggan.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnpelangganMouseExited

    private void btnpelangganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpelangganMousePressed
        // TODO add your handling code here:
        btnpelanggan.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnpelangganMousePressed

    private void btnpelangganMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpelangganMouseReleased
        // TODO add your handling code here:
        btnpelanggan.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnpelangganMouseReleased

    private void btnkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseEntered
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnkeluarMouseEntered

    private void btnkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseExited
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnkeluarMouseExited

    private void btnkeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMousePressed
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(58, 106, 135));
    }//GEN-LAST:event_btnkeluarMousePressed

    private void btnkeluarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseReleased
        // TODO add your handling code here:
        btnkeluar.setBackground(new Color(111, 200, 255));
    }//GEN-LAST:event_btnkeluarMouseReleased

    private void btnkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseClicked
        // TODO add your handling code here:
        Logout();
    }//GEN-LAST:event_btnkeluarMouseClicked

    public void Logout() {
        int a = JOptionPane.showConfirmDialog(null, "Switch User?");
        switch (a) {
            case JOptionPane.YES_OPTION:
                new FORM_SwitchUser().setVisible(true);
                this.dispose();
                break;
            case JOptionPane.NO_OPTION:
                System.exit(0);
            default:
                break;
        }
    }

    private void searchData() {
        tabelcd = new DefaultTableModel();
        table.setModel(tabelcd);
        tabelcd.addColumn("Username");
        tabelcd.addColumn("Password");
        tabelcd.addColumn("Nama");
        tabelcd.addColumn("Alamat");
        tabelcd.addColumn("KTP");
        tabelcd.addColumn("Telepon");
        tabelcd.addColumn("Jenis Kelamin");
        tabelcd.addColumn("Level");
        // menampilkan database ke dalam tabel
        String search = txt_search.getText();
        try {
            String sql = "SELECT * FROM data_karyawan WHERE username='" + search + "'"
                    + "or nama LIKE '%" + search + "%'";
            java.sql.Connection conn = (Connection) Connect.ConfigDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                tabelcd.addRow(new Object[]{
                    res.getString("username"),
                    res.getString("password"),
                    res.getString("nama"),
                    res.getString("alamat"),
                    res.getString("no_ktp"),
                    res.getString("no_telpn"),
                    res.getString("jenis_kelamin"),
                    res.getString("level"),});
            }
            table.setModel(tabelcd);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        searchData();

    }//GEN-LAST:event_txt_searchKeyReleased

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        String nama = txt_search.getText();
        if (txt_search.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan isi dahulu kolom \npencarian dengan username");
        } else {
            try {
                Statement statement = (Statement) Connect.ConfigDB().createStatement();
                statement.executeUpdate("delete from data_karyawan where username= ('" + nama + "');");
                showTable();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            } catch (HeadlessException | SQLException t) {
                JOptionPane.showMessageDialog(null, "Data gaagl dihapus");
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpelangganMouseClicked
        // TODO add your handling code here:
        new DashboardAdminPelanggan().setVisible(true);
    }//GEN-LAST:event_btnpelangganMouseClicked

    private void btnpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpegawaiActionPerformed
        // TODO add your handling code here:
        btnpegawai.setEnabled(false);
    }//GEN-LAST:event_btnpegawaiActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardAdminPegawai().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnpegawai;
    private javax.swing.JButton btnpelanggan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
