/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package index;

import java.awt.Color;

/**
 *
 * @author DFDIAG
 */
@SuppressWarnings("unchecked")
public class FORM_SwitchUser extends javax.swing.JFrame {

    /**
     * Creates new form FROM_switchUser
     */
    public FORM_SwitchUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPegawai = new javax.swing.JButton();
        ButtonAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPegawai.setBackground(new java.awt.Color(182, 220, 255));
        ButtonPegawai.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        ButtonPegawai.setText("PEGAWAI");
        ButtonPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonPegawaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonPegawaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonPegawaiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonPegawaiMousePressed(evt);
            }
        });
        getContentPane().add(ButtonPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, 210, 50));

        ButtonAdmin.setBackground(new java.awt.Color(182, 220, 255));
        ButtonAdmin.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        ButtonAdmin.setText("ADMIN");
        ButtonAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonAdminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonAdminMousePressed(evt);
            }
        });
        getContentPane().add(ButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 200, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/X PNG.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 70, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/1366x768/Switch_user.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPegawaiMouseClicked
        // TODO add your handling code here:
        new FORM_Login().setVisible(true);
    }//GEN-LAST:event_ButtonPegawaiMouseClicked

    private void ButtonPegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPegawaiMouseEntered
        // TODO add your handling code here:
        ButtonPegawai.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_ButtonPegawaiMouseEntered

    private void ButtonPegawaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPegawaiMousePressed
        // TODO add your handling code here:
        ButtonPegawai.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_ButtonPegawaiMousePressed

    private void ButtonPegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPegawaiMouseExited
        // TODO add your handling code here:
        ButtonPegawai.setBackground(new Color(182, 220, 255));
    }//GEN-LAST:event_ButtonPegawaiMouseExited

    private void ButtonAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAdminMouseClicked
        // TODO add your handling code here:
        new FORM_Login().setVisible(true);
    }//GEN-LAST:event_ButtonAdminMouseClicked

    private void ButtonAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAdminMouseEntered
        // TODO add your handling code here
        ButtonAdmin.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_ButtonAdminMouseEntered

    private void ButtonAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAdminMouseExited
        // TODO add your handling code here:
        ButtonAdmin.setBackground(new Color(182, 220, 255));
    }//GEN-LAST:event_ButtonAdminMouseExited

    private void ButtonAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAdminMousePressed
        // TODO add your handling code here:
        ButtonAdmin.setBackground(new Color(41, 128, 185));
    }//GEN-LAST:event_ButtonAdminMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_SwitchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_SwitchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_SwitchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_SwitchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_SwitchUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdmin;
    private javax.swing.JButton ButtonPegawai;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
