package index;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Connection.Connect;
import java.awt.HeadlessException;
import java.sql.SQLException;

public class FORM_Login extends javax.swing.JFrame {

    /**
     * Creates new form f_login
     */
    public FORM_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_login = new javax.swing.JPanel();
        txtuser = new javax.swing.JTextField();
        hide = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        btnmasuk = new javax.swing.JButton();
        LupaPassword = new javax.swing.JLabel();
        RegistrasiAkun = new javax.swing.JLabel();
        ButtonClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg_login.setBackground(new java.awt.Color(255, 255, 255));
        bg_login.setPreferredSize(new java.awt.Dimension(960, 540));
        bg_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtuser.setBackground(new java.awt.Color(218, 223, 252));
        txtuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(26, 26, 26));
        txtuser.setMargin(new java.awt.Insets(0, 25, 0, 25));
        txtuser.setSelectionColor(new java.awt.Color(107, 125, 253));
        bg_login.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 360, 35));

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/MATA SILANG PNG.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hideMouseReleased(evt);
            }
        });
        bg_login.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 50, 30));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/show.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showMousePressed(evt);
            }
        });
        bg_login.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, -1, 50));

        txtpass.setBackground(new java.awt.Color(218, 223, 252));
        txtpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpass.setForeground(new java.awt.Color(26, 26, 26));
        txtpass.setMargin(new java.awt.Insets(0, 25, 0, 50));
        txtpass.setSelectionColor(new java.awt.Color(107, 125, 253));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        bg_login.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 360, 35));

        btnmasuk.setBackground(new java.awt.Color(51, 153, 255));
        btnmasuk.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnmasuk.setForeground(new java.awt.Color(26, 26, 26));
        btnmasuk.setText("MASUK");
        btnmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasukActionPerformed(evt);
            }
        });
        bg_login.add(btnmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 280, 40));

        LupaPassword.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        LupaPassword.setForeground(new java.awt.Color(26, 26, 26));
        LupaPassword.setText("Lupa Kata Sandi ?");
        LupaPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LupaPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LupaPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LupaPasswordMouseClicked(evt);
            }
        });
        bg_login.add(LupaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, -1, -1));

        RegistrasiAkun.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        RegistrasiAkun.setForeground(new java.awt.Color(26, 26, 26));
        RegistrasiAkun.setText("Registrasi akun |");
        RegistrasiAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrasiAkun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrasiAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrasiAkunMouseClicked(evt);
            }
        });
        bg_login.add(RegistrasiAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        ButtonClose.setForeground(new java.awt.Color(0, 51, 51));
        ButtonClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/X PNG.png"))); // NOI18N
        ButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCloseMouseClicked(evt);
            }
        });
        bg_login.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/LOGIIN.jpg"))); // NOI18N
        bg_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int attempt = 1;

    private void btnmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasukActionPerformed
        try {
            String sql = " SELECT * FROM data_karyawan WHERE username ='"
                    + txtuser.getText() + "'AND password='"
                    + txtpass.getText() + "'";
            java.sql.Connection conn = (Connection) Connect.ConfigDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);

            if (rs.next()) {
                if (rs.getString("level").equals("admin")) {            // ====== tingkatan / status akun level-admin akan masuk kedalam dashboard admin
                    new DashboardAdminPegawai().setVisible(true);       // membuka Dashboard admin 
                    new notificationBerhasil().setVisible(true);        // menampilkan notifikasi Berhasil 
                } else if (rs.getString("level").equals("pegawai")) {   // ====== Jika bukan tingkatan admin maka yang akan dieksekusi baris ini yaitu level "pegawai"
                    new DashboardPegawaiJasa().setVisible(true);        // membuka Dashboard pegawai 
                    new notificationBerhasil().setVisible(true);        // menampilkan notifikasi Berhasil 
                }
            } else {
                if (attempt <= 3) { // jika percobaan kurang dari = 3 (4x percobaan) akan di meneksekusi else 
                    JOptionPane.showMessageDialog(this, "Access Ditolak! \n Percobaan :" + attempt + "/3");
                    attempt++; // statement menambahkan 1 angka setiap percobaan 
                } else {
                    JOptionPane.showMessageDialog(this, "Program akan dihentikan! \n Silahkan reset password atau konfirmasi ke admin :D"); // statement akhir ketika telah salah 3x
                    System.exit(0);
                }
            }
        } catch (HeadlessException | SQLException e) { // menampilkan pesan eror 
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnmasukActionPerformed

    private void RegistrasiAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrasiAkunMouseClicked
        this.setVisible(false);
        new FORM_Registrasi().setVisible(true);
    }//GEN-LAST:event_RegistrasiAkunMouseClicked

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        // TODO add your handling code here:
        if (show.isEnabled()) {
            txtpass.setEchoChar((char) 0);
        } else {
            txtpass.setEchoChar('*');

        }
    }//GEN-LAST:event_showMouseClicked

    private void showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMousePressed

//        if (mata.isVisible()) {
//            txt_password.setEchoChar((char) 0);
//        } else {
//            hide.isVisible();
//            txt_password.setEchoChar('*');
//        }
//        show.setVisible(true);
//        hide.setVisible(false);
//        txt_password.setEchoChar((char) 0);
    }//GEN-LAST:event_showMousePressed

    private void hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMousePressed
        // TODO add your handling code here:
        show.setVisible(true);
        hide.setVisible(false);
        txtpass.setEchoChar((char) 0);
    }//GEN-LAST:event_hideMousePressed

    private void hideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseReleased
        // TODO add your handling code here:
        show.setVisible(false);
        hide.setVisible(true);
        txtpass.setEchoChar('*');
    }//GEN-LAST:event_hideMouseReleased

    private void ButtonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new FORM_SwitchUser().setVisible(true);
    }//GEN-LAST:event_ButtonCloseMouseClicked

    private void LupaPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LupaPasswordMouseClicked
        this.dispose();
        new FORM_LupaPassword().setVisible(true);
    }//GEN-LAST:event_LupaPasswordMouseClicked

    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonClose;
    private javax.swing.JLabel LupaPassword;
    private javax.swing.JLabel RegistrasiAkun;
    private javax.swing.JPanel bg_login;
    private javax.swing.JButton btnmasuk;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

}
