package index;

import Connection.Connect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

public class input_jasa extends javax.swing.JFrame {

    /**
     * Creates new form input_jasa
     */
    public input_jasa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbStatus = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        txt_nama = new javax.swing.JTextField();
        txt_telepon = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_biaya = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        cbJenisLaundry = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        txt_beratBarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_hitung = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_dataPakaian1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_bayar = new javax.swing.JTextField();
        txt_kembali = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        cbStatus.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "progress" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(960, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nama.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 210, -1));

        txt_telepon.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jPanel1.add(txt_telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 210, -1));

        txt_alamat.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 210, -1));

        txt_biaya.setEditable(false);
        txt_biaya.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jPanel1.add(txt_biaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 210, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("/kg");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, 20));

        txt_tanggal.setEditable(false);
        txt_tanggal.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jPanel1.add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 220, -1));

        btn_submit.setText("SUMBIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 110, 30));

        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 110, 30));

        cbJenisLaundry.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cbJenisLaundry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "kering", "mamel" }));
        cbJenisLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisLaundryActionPerformed(evt);
            }
        });
        jPanel1.add(cbJenisLaundry, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 100, 20));

        txt_harga.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 100, -1));

        txt_beratBarang.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jPanel1.add(txt_beratBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/X PNG.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 30, 20));

        btn_hitung.setText("HITUNG");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 100, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Berat Barang");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 120, 40));

        txt_dataPakaian1.setColumns(20);
        txt_dataPakaian1.setLineWrap(true);
        txt_dataPakaian1.setRows(3);
        txt_dataPakaian1.setWrapStyleWord(true);
        txt_dataPakaian1.setAutoscrolls(false);
        jScrollPane2.setViewportView(txt_dataPakaian1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 220, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 110, 20));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Bayar");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("progress");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 110, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Kembali");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 100, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, 30));

        txt_bayar.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
        });
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 210, -1));

        txt_kembali.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jPanel1.add(txt_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 210, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/InputJasaReal.jpg"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void tanggal() {
        DateFormat tgl = new SimpleDateFormat("Y-M-d k:m:s");
        String htgl = tgl.format(Calendar.getInstance().getTime());
        txt_tanggal.setText(htgl);
    }

    private void kosong() {
        txt_nama.setText(null);
        txt_telepon.setText(null);
        txt_alamat.setText(null);
        txt_harga.setText(null);
        txt_kembali.setText(null);
        txt_bayar.setText(null);
        txt_beratBarang.setText(null);
        cbJenisLaundry.setSelectedIndex(0);
        txt_biaya.setText(null);
        txt_tanggal.setText(null);
        cbStatus.setSelectedIndex(0);
        txt_dataPakaian1.setText(null);
    }
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void kembali() {
        this.setVisible(false);
        try {
            new DashboardPegawaiJasa().setVisible(true);
        } catch (Exception e) {
        }
    }

    private void total_biaya() {
        if (txt_beratBarang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Berat Barang belum diisi");
        } else {
            double harga = Double.parseDouble(txt_harga.getText()),
                    beratBarang = Double.parseDouble(txt_beratBarang.getText()),
                    totalharga;
            totalharga = (beratBarang * harga);
            txt_biaya.setText("" + totalharga);
            tanggal();
        }
    }

    private void kembalian() {
        if (txt_biaya.getText().isEmpty()) {                 //jika data berat kosong maka menampilkan informasi berat barang belum diisi
            JOptionPane.showMessageDialog(null, "Berat Barang belum diisi / Hitung biaya");
        } else {
            double total_biaya = Double.parseDouble(txt_biaya.getText()),
                    bayar = Double.parseDouble(txt_bayar.getText()),
                    kembaliannya;
            kembaliannya = (bayar - total_biaya);
            txt_kembali.setText("" + kembaliannya);
            tanggal();
        }
    }

    private void cbJenisLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisLaundryActionPerformed
        // TODO add your handling code here:

        switch (cbJenisLaundry.getSelectedIndex()) {
            case 0:
                txt_harga.setText("");
                txt_biaya.setText("");
                break;
            case 1:
                txt_harga.setText("4000");
                break;
            case 2:
                txt_harga.setText("3500");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbJenisLaundryActionPerformed


    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try {
            String sql = "INSERT INTO `data_pelanggan` "
                    + "(`nama`, \n"
                    + "`telepon`, \n"
                    + "`alamat`, \n"
                    + "`berat_barang`, \n"
                    + "`jenis_laundry`, \n"
                    + "`harga`, \n"
                    + "`biaya`, \n"
                    + "`bayar`, \n"
                    + "`kembali`, \n"
                    + "`status`, \n"
                    + "`tanggal`, \n"
                    + "`data_pakaian`)VALUES('"
                    + txt_nama.getText() + "','"
                    + txt_telepon.getText() + "','"
                    + txt_alamat.getText() + "','"
                    + txt_beratBarang.getText() + "','"
                    + cbJenisLaundry.getSelectedItem() + "','"
                    + txt_harga.getText() + "','"
                    + txt_biaya.getText() + "','"
                    + txt_bayar.getText() + "','"
                    + txt_kembali.getText() + "','"
                    + "progress','"
                    + txt_tanggal.getText() + "','"
                    + txt_dataPakaian1.getText() + "')";
            java.sql.Connection conn = (Connection) Connect.ConfigDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasill");
            this.dispose();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        total_biaya();
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        kembalian(); // menghitung dan menginput kembalian
    }//GEN-LAST:event_txt_bayarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_jasa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new input_jasa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cbJenisLaundry;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_beratBarang;
    private javax.swing.JTextField txt_biaya;
    private javax.swing.JTextArea txt_dataPakaian1;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tanggal;
    private javax.swing.JTextField txt_telepon;
    // End of variables declaration//GEN-END:variables

}
